# Server port

port: 8317
# Management API settings
remote-management:
  # Whether to allow remote (non-localhost) management access.

  # When false, only localhost can access management endpoints (a key is still required).
  allow-remote: false
  # Management key. If a plaintext value is provided here, it will be hashed on startup.

  # All management requests (even from localhost) require this key.

  # Leave empty to disable the Management API entirely (404 for all /v0/management routes).
  secret-key: "$2a$10$yhuXLDtc.UZA772J0itWGuhef4.c29yfAkb7wWBB1Q3WPc2bG4vEe"
# Authentication directory (supports ~ for home directory)
auth-dir: "/root/.cli-proxy-api"
# Enable debug logging
debug: false
# Proxy URL. Supports socks5/http/https protocols. Example: socks5://user:pass@192.168.1.1:1080/

#proxy-url: ""

# Number of times to retry a request. Retries will occur if the HTTP response code is 403, 408, 500, 502, 503, or 504.
request-retry: 3
# Quota exceeded behavior
quota-exceeded:
  switch-project: true # Whether to automatically switch to another project when a quota is exceeded
  switch-preview-model: true # Whether to automatically switch to a preview model when a quota is exceeded
# API keys for authentication
api-keys:
  - "sk-820515"
# API keys for official Generative Language API
generative-language-api-key:
  - "AIzaSyDycCg0hYxfJ0PPxWwYdhwKawfhiRr1jdY"
  - "AIzaSyB6XRvsCYdmwGurQHYgBTP_XGbv-H1ovPc"
  - "AIzaSyBTlpxd1i4Rf7v9lgnZhkVuAS0bKmeSyi4"
  - "AIzaSyC2jCkzjNX_WNC5nWSCBq29cMDs6cDCnEo"
  - "AIzaSyBKkmA0unBC7N7RsX-eX3szVy6cmm-poLI"
# Codex API keys（若支持自定义base-url，保持字典格式；若不支持，可简化为字符串列表）
codex-api-key:
  - api-key: "sk-atSM..."
    base-url: "https://www.example.com" # use the custom codex API endpoint
# Claude API keys（同上，支持自定义base-url）
claude-api-key:
  - api-key: "sk-atSM..." # use the official claude API key, no need to set the base url
    base-url: ""
  - api-key: "sk-atSM..."
    base-url: "https://www.example.com" # use the custom claude API endpoint
# OpenAI compatibility providers（修正缩进，确保子项比父级多2个空格）
openai-compatibility:
  - name: "iflow" # The name of the provider; it will be used in the user agent and other places.
    base-url: "https://apis.iflow.cn/v1" # The base URL of the provider.
    api-keys: # The API keys for the provider. Add multiple keys if needed. Omit if unauthenticated access is allowed.
      - "sk-8320e756312bd852b2c99764372313d0"
      - "sk-b7158c3096ab9e26042834a215b4880f"
      - "sk-bcc1fc26a70d2a768b32942002bef4f7"
    models: # The models supported by the provider.
      - name: "kimi-k2-0905" # The actual model name.
        alias: "kimi-k2" # The alias used in the API.
  - name: "openrouter"
    base-url: "https://openrouter.ai/api/v1"# The base URL of the provider.
    api-keys: # The API keys for the provider. Add multiple keys if needed. Omit if unauthenticated access is allowed.
      - "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"
      - "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"
      - "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"
      - "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"
    models: # The models supported by the provider.
       - name: "x-ai/grok-4-fast:free" # The actual model name.
         alias: "grok-4-fast" # The alias used in the API.


